apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valodzia.fullname" . }}
  labels:
  {{- include "valodzia.labels" . | nindent 4 }}
type: Opaque
data:
  SPACE_CLIENT_ID: {{ .Values.space.clientID | b64enc | quote }}
  SPACE_CLIENT_SECRET: {{ .Values.space.clientSecret | b64enc | quote }}
  SPACE_SERVER_URL: {{ .Values.space.serverURL | b64enc | quote }}

